### ISSUE TITLE
RuntimeError and compile error upon compiling Sass file

### ISSUE THREAD

**Issue by fnky** [saenzramiro/rambox#1058]
### Steps to reproduce

1. Install dependencies based on the [environment](https://github.com/saenzramiro/rambox#environment).
    - Including Compass 1.0.3
2. Run the commands as mentioned in [quickstart](https://github.com/saenzramiro/rambox#quickstart) to compile a production build.

### Expected behavior

It should build and run the application without any errors.

### Actual behavior

Either it doesn't compile and throws an error when compiling `Rambox-all.scss`:

```
    error Rambox-all.scss (/Users/fnky/Git/rambox/ext/packages/ext-theme-base/sass/utils.rb:30:in `parsebox': can't modify frozen Array)
Compilation failed in 1 files.
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExProcess: compass process exited with non-zero code : 1
[ERR] 	at c
[ERR] om.sencha.command.Sencha.dispatch(Sencha.java:79)
[ERR]
[ERR] Total time: 15 seconds
[ERR] The following error occurred while executing this line:
/Users/fnky/Git/rambox/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/Users/fnky/Git/rambox/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/Users/fnky/Git/rambox/.sencha/app/sass-impl.xml:235: com.sencha.exceptions.ExProcess: compass process exited with non-zero code : 1
error Command failed with exit code 65.
```

Sometimes it does compile successfully but the following output will be printed to `Rambox-all.css`:

```
/*
RuntimeError: can't modify frozen Array

Backtrace:
/Users/fnky/Git/rambox/ext/packages/ext-theme-base/sass/utils.rb:30:in `parsebox'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:140:in `_perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:403:in `visit_return'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:248:in `block (3 levels) in perform_sass_fn'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:248:in `each'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:248:in `block (2 levels) in perform_sass_fn'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:247:in `catch'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:247:in `block in perform_sass_fn'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:244:in `perform_sass_fn'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:131:in `_perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/operation.rb:64:in `_perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:170:in `perform_arg'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `block in _perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `each'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `each_with_index'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `each'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `map'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:124:in `_perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/list_literal.rb:63:in `block in _perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/list_literal.rb:63:in `map'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/list_literal.rb:63:in `_perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:469:in `visit_variable'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `map'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:88:in `block in with_import'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:88:in `with_import'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/engine.rb:278:in `render'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:492:in `update_stylesheet'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:209:in `each'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/sass_compiler.rb:40:in `compile!'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/commands/update_project.rb:49:in `perform'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/bin/compass:44:in `call'
/Users/fnky/.rbenv/versions/2.1.2/gemsets/devset/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
/Users/fnky/bin/Sencha/Cmd/6.1.2.15/extensions/sencha-compass/gems/bin/compass:23:in `load'
/Users/fnky/bin/Sencha/Cmd/6.1.2.15/extensions/sencha-compass/gems/bin/compass:23:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "RuntimeError: can't modify frozen Array"; }
```

Caused by the line in [`ext/packages/ext-theme-base/sass/utils.rb:30`](https://github.com/saenzramiro/rambox/blob/master/ext/packages/ext-theme-base/sass/utils.rb#L30)

### ENVIRONMENT

- Ruby 2.3.4 (`ruby 2.3.4p301`)
- Compass 1.0.3
- Sencha Cmd 6.1.2.15

> Rambox: [`master`](https://github.com/saenzramiro/rambox)
> OS: macOS Sierra 10.12.3
> Arch: x64

**Comment by Ash258** [comment]
I guess it's not relevant anymore? Tested building on lots of variations of workspaces (windows, linux, macos, docker) and working as expected.
