### ISSUE TITLE
a Javascipt erroragain

### ISSUE THREAD

**Issue by Vidarius** [saenzramiro/rambox#438]
Version: 0.4.4 win32(64)  - portable
Electron: 1.4.1
Chromeium: 53.0.2785.113
Node: 6.5.0

![a javacript error again](https://cloud.githubusercontent.com/assets/20396855/19796708/8682f0c2-9ce6-11e6-8abb-2d29c7f0569c.jpg)

**Comment by Pablohn26** [comment]
I guess I have the same problem while upgrading with deb package to Rambox 0.4.5

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/Rambox/resources/app.asar/resources/IconTrayUnread.png
    at TypeError (native)
    at Object.exports.setBadge (/opt/Rambox/resources/app.asar/electron/tray.js:69:10)
    at updateBadge (/opt/Rambox/resources/app.asar/electron/main.js:232:7)
    at BrowserWindow.mainWindow.on (/opt/Rambox/resources/app.asar/electron/main.js:177:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:191:7)
    at WebContents.webContents.on (/opt/Rambox/resources/electron.asar/browser/api/browser-window.js:49:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:194:7)
    at Immediate.setImmediate (/opt/Rambox/resources/electron.asar/browser/api/web-contents.js:237:17)
```

It was completely stuck always displaying same error. Closing Rambox and opening again shows Rambox upgraded and that error not diplayed anymore. So I do not know how to reproduce the error (maybe on a clean environment installing Rambox 0.4.4 and then upgrading to 0.4.5)

**Comment by white-gecko** [comment]
I have the same on 0.5.14 debian x64:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/Rambox/resources/app.asar/resources/IconTrayUnread.png
    at Object.exports.setBadge (/opt/Rambox/resources/app.asar/electron/tray.js:76:10)
    at updateBadge (/opt/Rambox/resources/app.asar/electron/main.js:278:7)
    at BrowserWindow.mainWindow.on (/opt/Rambox/resources/app.asar/electron/main.js:217:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:194:7)
    at WebContents.webContents.on (/opt/Rambox/resources/electron.asar/browser/api/browser-window.js:81:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:197:7)
```
