### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by dharjai** [saenzramiro/rambox#668]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\app.asar\resources\IconTrayUnread.ico
    at TypeError (native)
    at Object.exports.setBadge (C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\app.asar\electron\tray.js:69:10)
    at updateBadge (C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\app.asar\electron\main.js:239:7)
    at BrowserWindow.mainWindow.on (C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\app.asar\electron\main.js:176:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:191:7)
    at WebContents.webContents.on (C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\electron.asar\browser\api\browser-window.js:83:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:194:7)
    at Immediate.setImmediate (C:\Users\Dinesh\AppData\Local\Rambox\app-0.5.3\resources\electron.asar\browser\api\web-contents.js:249:12)

[OK]

**Comment by saenzramiro** [comment]
Can you explain when this error appears? Can you record a video displaying this error please?

**Comment by dharjai** [comment]
Dear Sir

Thanks for reply, error occurs after I close the app on win 10 and re 
open it.

Reagrds


Dinesh



------ Original Message ------

**Comment by saenzramiro** [comment]
Are you using the original build or did you built your own?

**Comment by dharjai** [comment]
Original

Dear Sir

Regards

Dinesh
On 08-02-2017 20:31:58, Ramiro Saenz <notifications@github.com> wrote:
Are you using the original build or did you built your own?

**Comment by xorander00** [comment]
I'm seeing this as well.

TypeError: Error processing argument at index 0, conversion failure from
  Rambox\app-0.5.9\resources\app.asar\resources\Icon.ico
at Object.exports.setBadge

**Comment by saenzramiro** [comment]
Is this still happening in v0.5.10?

**Comment by dzeidzei** [comment]
I'm getting this occasionally in 0.5.13. when tray icon changes. 
conversion failure from IconTrayUnread.ico to object.exports.setBadge
or
conversion failure from Icon.ico to object.exports.setBadge
Depending on currently showing icon.

In 0.5.13 tray.js error happens in line 76. 

When this happens once it starts to happen every time tray icon is changing. Rambox restart fixes it.
I assume that 'Show System Tray indicator on unread messages' uncheck prevents this problem to occur.

**Comment by dzeidzei** [comment]
Last line of previous message appears to be false. Error still occurs even though 'Show System Tray indicator on unread messages' is unhecked.
