### ISSUE TITLE
icloud has stopped responding

### ISSUE THREAD

**Issue by tgt-anasr** [saenzramiro/rambox#749]
### Steps to reproduce

1. Use RamBox in Arch Linux
2. Add iCloud

### Expected behavior

Login window should appear.

### Actual behavior

An error happens

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Arch Linux 

> Arch: x64

**Comment by rygos** [comment]
This happens for me, too.

![image](https://cloud.githubusercontent.com/assets/1985803/24496218/e5be2970-1537-11e7-933f-0f3d4173327b.png)

```ERROR
Cannot read property 'contentWindow' of undefined. The calling function is TypeError:     at HTMLDocument.set (<anonymous>:1:119)
    at .titleDidChange (

FILE
Unknown

LINE
Unknown

STACK
TypeError: Cannot read property 'contentWindow' of undefined
    at HTMLDocument.set (<anonymous>:1:119)
    at .titleDidChange (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:889:1065)
    at _notifyPropertyObservers (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:69:384)
    at propertyDidChange (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:65:1052)
    at set (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:64:1254)
    at .<anonymous> (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:90:480)
    at set (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:890:54)
    at .updateTitle (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:889:270)
    at run (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:840:637)
    at r.<anonymous> (https://icloud.cdn-apple.com/system/cloudos/17BHotfix5/en-us/javascript-packed.js:950:153)

MOST RECENT STACK
SC.run
  >  args:  function (){i.apply(s,r
)},  undefined,  undefined,  undefined,  undefined
SC.Module._invokeCallback
  >  args:  cloudos_foundation/language,  SC.Application:sc1025,  function (){window.localeDidLoad=!0,SC.Event.add(document,"mousemove",function(e){var t=CloudOS.appController.getPath("currentApp"),n={clientX:e.clientX,clientY:e.clientY},r;if(!t||!t.get("contentWindow")||!t.get("isReady"))return YES;t.passMessage("_mouseMove",n)}),SC.Event.add(document,"mouseup",function(e){var t=CloudOS.appController.getPath("currentApp"),n={clientX:e.clientX,clientY:e.clientY},r;if(!t||!t.get("contentWindow")||!t.get("isReady"))return YES;t.passMessage("_mouseUp",n)}),Object.defineProperty&&Object.defineProperty(window,"currentApp",{get:function(){return CloudOS.appController.getPath("currentApp.contentWindow")}});if(CloudOS.get("isCloudOSMini")){var e=CloudOS.appController.getDefaultAppName();CloudOS.displayApps.push({name:e,isDynamicallyLoaded:YES})}else CloudOSBootstrap.isOnSupportedMobile||SC.Module.loadModule("cloudos_foundation/springboard",this,function(){CloudOS.configureSpringboard()
});CloudOS.getPath("mainPage.mainPane").append(),SC.debug("CloudOS.main() already has localized strings, proceeding to run CloudOS.run() now."),CloudOS.run(),CloudOS.invokeDelegateMethod(t,"applicationDidStart"),CloudOS.set("mainHasCompleted",YES)},  cloudos_foundation/language,  undefined
function (){SC.Module._invokeCallback(e,t,n,r)}
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.Module._invokeCallbacksForModule
  >  args:  cloudos_foundation/language,  undefined,  undefined,  undefined,  undefined
SC.Module._moduleDidBecomeReady
  >  args:  cloudos_foundation/language,  undefined,  undefined,  undefined,  undefined
function (){n.isReady=YES,this._moduleDidBecomeReady(e)}
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.ObserverSet.invokeMethods
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.Object#_flushinvokeLastQueue
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.Object#flushAllPending
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.Object#endRunLoop
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
function (){var i=n[r],s;if(!i)throw new Error("No '"+r+"' method was found on the superclass");return t.isEnhancement?s=Array.prototype.slice.call(ar
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.RunLoop#endRunLoop
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.Object.end
  >  args:  undefined,  undefined,  undefined,  undefined,  undefined
SC.run
  >  args:  function (){i.apply(s,r
)},  undefined,  undefined,  undefined,  undefined
(Because SC.run was called recursively, no more of the stack is available)


IS FATAL
true

TYPE
exception

APPLICATION NAME
cloudos

APP STATECHART
SC.Statechart:sc1155
  initialized: true
  name: cloudos-statechart
  current-states: [
    loading
  ]
  state-transition:
    active: false
    suspended: false
  handling-event: false


BUILD NUMBER
17BHotfix5

MASTERING NUMBER
17BHotfix5

TIME
Thu Mar 30 2017 10:57:24 GMT+0200 (Mitteleuropäische Sommerzeit)        (1490864244415)

HOST
www.icloud.com

USER AGENT
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

ENVIRONMENT
PROD

RECENT LOG MESSAGES
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: Adding new link tag with href = '/system/cloudos/17BHotfix5/de-de/stylesheet-packed.css'.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Attempting to load 'cloudos_foundation/language'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Module 'cloudos_foundation/language' is not loaded, loading now.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Loading CSS file in 'cloudos_foundation/language' -> '/system/cloudos/17BHotfix5/cloudos_foundation/language/17BHotfix5/de-de/stylesheet.css'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Loading JavaScript file in 'cloudos_foundation/language' -> '/system/cloudos/17BHotfix5/cloudos_foundation/language/17BHotfix5/de-de/javascript-strings.js'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: Removing old link tag with href = '/system/cloudos/17BHotfix5/en-us/stylesheet-packed.css'.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Module 'cloudos_foundation/language' finished loading.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Evaluating and invoking callbacks for 'cloudos_foundation/language'.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Module 'cloudos_foundation/language' has completed loading, invoking callbacks.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Attempting to load 'cloudos_foundation/springboard'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Module 'cloudos_foundation/springboard' is not loaded, loading now.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Loading CSS file in 'cloudos_foundation/springboard' -> '/system/cloudos/17BHotfix5/cloudos_foundation/springboard/17BHotfix5/de-de/stylesheet.css'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: SC.Module: Loading JavaScript file in 'cloudos_foundation/springboard' -> '/system/cloudos/17BHotfix5/cloudos_foundation/springboard/17BHotfix5/de-de/javascript.js'
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: CloudOS.main() already has localized strings, proceeding to run CloudOS.run() now.
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: CloudOS window is visible initially
Thu, 30 Mar 2017 08:57:23 GMT:  DEBUG: Loading localized strings and metrics
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: -->  Request 1:   GET to https://www.icloud.com/applications/newspublisher/current/info.json,  headers: Content-Type=text/plain,  body: (omitted)
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: BEGIN initialize statechart
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: BEGIN gotoState: __ROOT_STATE__
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: starting from current state: ---
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: current states before: ---
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: --> entering state: __ROOT_STATE__
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: --> entering state: loading
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  Trying to load font SFNSText
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: current states after: loading
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: END gotoState: __ROOT_STATE__
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  SC.Statechart<cloudos-statechart, sc1155>: END initialize statechart
Thu, 30 Mar 2017 08:57:24 GMT:  INFO:  Spent 214 ms symbolicating
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: CloudKit: ErrorCatcher dialog invoked.
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Attempting to load 'cloudkit/error_catcher'
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Module 'cloudkit/error_catcher' is not loaded, loading now.
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Loading CSS file in 'cloudkit/error_catcher' -> '/system/cloudos/17BHotfix5/cloudkit/error_catcher/17BHotfix5/de-de/stylesheet.css'
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Loading JavaScript file in 'cloudkit/error_catcher' -> '/system/cloudos/17BHotfix5/cloudkit/error_catcher/17BHotfix5/de-de/javascript-strings.js'
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: Language check for CloudOS: null -> de-de. We WILL relocalize cloudOS.
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: <--  Response 1:  200  (393ms),  headers: Accept-Ranges=bytes, Access-Control-Allow-Origin=*, Cache-Control=public, max-age=300, Content-Encoding=gzip, Content-Language=en-us, Content-Length=171, Content-Type=application/json, Date=Thu, 30 Mar 2017 08:56:51 GMT, ETag="fd-548364dd82cc0", Server=Apache, Vary=Accept-Encoding, X-Responding-Instance=anton-apache:22503@st14p25ic-hpaf08101201:9081:1M34  body: (omitted)
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: Adding additional data for newspublisher
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: Since there is no account prefs yet, we will set the locale of “newspublisher” as en-us
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Module 'cloudkit/error_catcher' finished loading.
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Evaluating and invoking callbacks for 'cloudkit/error_catcher'.
Thu, 30 Mar 2017 08:57:24 GMT:  DEBUG: SC.Module: Module 'cloudkit/error_catcher' has completed loading, invoking callbacks.

```

**Comment by saenzramiro** [comment]
Can anyone translate the previous image attached?

**Comment by SimJoSt** [comment]
> "iCloud" has stopped responding.
> 
> The program was interrupted due to an error. You can help Apple improve our products by providing us with diagnostic and usage information by sending it to us via iCloud.
> 
> -> Details
> If you click on "Send to Apple", you accept that Apple may collect this information in the scope of support services and use it to improve products and services. This report includes personalized data like your user name and user data. You can find more infromation about Apples privacy guideline at https://www.apple.com/privacy/
> 
> 
> Reload | Send to Apple

**Comment by saenzramiro** [comment]
Thanks @SimJoSt! I will investigate.

**Comment by GroundJet** [comment]
Xubuntu 16.10 here, same problem, a small log that might help:

**Comment by tgt-anasr** [comment]
Looks like a Linux related error
